default:
  service:
    PORT: "PORT"
    MONGODBURL: "MONGO_URL"
    LOGSENETOKEN: "LOGSENE_TOKEN"
    WITTOKEN: "WITTOKEN"
    TWITTER_CONSUMER_KEY : "TWITTER_CONSUMER_KEY"
    TWITTER_CONSUMER_SECRET: "TWITTER_CONSUMER_SECRET"
    TWITTER_TOKEN: "TWITTER_TOKEN"
    TWITTER_SECRET: "TOKEN_SECRET"
