default:
  service:
    SERVICEVERSION: v1
    PORT: 8787
    MONGODBURL: "mongodb://localhost:27017/knockthon"
    LOGSENETOKEN: "e5d9ee73-7179-4c17-a5ab-aca21c66851d"
    JWT: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjIwNTgsImlhdCI6MTUwMzA0ODI1NywiZXhwIjoxNTEwODI0MjU3fQ.Dwfvyu3_qQ-UT3ZKeLfckRXtYQCJqrauknidLT-nM2o"
    TASKID: 1991
    WITTOKEN : "BPQTQ7I45PX6BDVVSHZRW5AYLHBFUVR4"
    SERVICENAME : "http://172.16.1.134:8787/v1/"
    TWITTER_CONSUMER_KEY: "9sIrl5JtGfGvMwIRCsfZ7JKtF"
    TWITTER_CONSUMER_SECRET: "FSc3H5V0CyjkClpfBJQJt6XpFHwdd8k6vzjiqgDYmoUiNVOWAH"
    TWITTER_TOKEN: "898594475554914308-dLSHBLQyPpprH8tkPMWmVmXkWklumEi"
    TWITTER_SECRET: "1C01xk71yaf9iYD0QxOQbEx65m5eTk3rrmGieNqoEQxNi"
